### PR TITLE
FIX off-by-one in script

### PR DESCRIPTION
**Pull request by NelleV**

### CODE REVIEW

**Comment by NelleV** [comment]
@nservant The bug should be fixed. I'm waiting for the tests to pass.
Do you want me to release a minor version?

**Comment by nservant** [comment]
yes please, with an update on anaconda :)

**Comment by nservant** [comment]
so did you check the `--base` parameter ? should we ask for `--base 1` in HiC-Pro ?

**Comment by NelleV** [comment]
@nservant The base parameter is set to 1 by default, so we should be good with nothing in HiC-pro. The minor detail is that it will be verbose if we don't provide it.

**Pull request merged**
